润色第一章
FreeBSD-Ask/Handbook pull request #108
Opened 2023-06-18 08:38 UTC by HeavySnowJakarta

第一章各部分视情况润色了2-4遍罢。虽然仍有不满意的地方，但是总体上不会像隔壁苏珊太太家的苹果派一样令人感觉糟糕了。

以下几个地方可能值得注意：
* 1.3.4 一节“你所编译的每个 port 的完整原始文件都是动态检索的”这一句我没看懂。我觉得这么译不对劲。
* 1.2 概述一章“而不是硬编码行为的单体‘一体化’守护程序。”是否应再清楚些？举几个 systemd 之类的例子？
* 1.3.4 “除了基本的发行版之外，FreeBSD 还提供了一个移植软件集（port/ports）”后文提到了“port”这个词及其复数形式。不熟悉“port”概念的人可能会对这一术语感到疑惑，因此我认为应当对其进行适当说明（比如在前面可能不太适当地用括号注明一下）。另外某些不熟悉英语的人可能会对“port”和“ports”这两个词的差异产生疑惑，所以我很不负责任地同时注明了这两个词。

为了尽可能地改掉原版的翻译腔问题，我对几句话完全重写了一下，有的地方我选择彻底破坏掉原文的结构、顺序与用语，代价是不可能完全传达原文的含义。由于我没有查阅英文原文，如果我润色前的版本与英文原文一致，那么读者至少可以领会原文基本希望表达的意思。

2023-06-18 09:09 UTC, ykla requested changes
请修改一下。非常感谢。

2023-06-18 09:09 UTC, ykla commented on di-1-zhang-jian-jie/1.2.-huan-ying-lai-dao-freebsd.md
> +* _自由的开源许可证_，它授予你自由修改和扩展其源代码的权力，并可将其纳入开源项目和闭源的产品中，而不会施加典型的著作权限制，同时也避免了潜在的许可证不兼容的问题。
这里是“著佐权”不是“著作权”，翻译前请阅读 https://handbook.bsdcn.org/yi-zhe-shuo-ming.html

2023-06-18 09:09 UTC, ykla commented on di-1-zhang-jian-jie/1.3.-guan-yu-freebsd-xiang-mu.md
这里应该保持“开发模式”，因为不是代码本身的撰写

2023-06-18 09:09 UTC, ykla commented on di-1-zhang-jian-jie/1.3.-guan-yu-freebsd-xiang-mu.md
> +最后，但绝对非常重要地，最大的开发者群体是用户自己，他们几乎一直在向我们提供反馈和错误修正。联系 FreeBSD 基本系统开发团队的主要方式是订阅 [FreeBSD 技术讨论邮件列表](https://lists.freebsd.org/subscription/freebsd-hackers)。对于第三方应用程序的移植，应该订阅 [FreeBSD ports 邮件列表](https://lis
不应该强调“对于英文原文文档”，因为没有其他语言可选。

2023-06-18 09:09 UTC, ykla commented on di-1-zhang-jian-jie/1.3.-guan-yu-freebsd-xiang-mu.md
> +除了基本的发行版之外，FreeBSD 还提供了一个移植软件集（port/ports），其中有成千上万的常用程序。ports 列表的范围从 HTTP 服务器，到游戏、语言、编辑器，以及几乎所有介于两者之间的东西。大约有 36000 个 port；整个 ports 大约需要 3GB。要编译一个 port，你只需切换到你希望安装的程序的目录，键入 `make install`，然后让系统完成剩下的工作
这里应该是指 ports，二者区别可以写到 术语表当中。

2023-06-18 09:11 UTC, ykla commented
>>1.2 概述一章“而不是硬编码行为的单体‘一体化’守护程序。”是否应再清楚些？举几个 systemd 之类的例子？

你有更好的例子吗，我可以看看能否提交到上游中去。

2023-06-18 12:47 UTC, HeavySnowJakarta commented on di-1-zhang-jian-jie/1.3.-guan-yu-freebsd-xiang-mu.md
> +最后，但绝对非常重要地，最大的开发者群体是用户自己，他们几乎一直在向我们提供反馈和错误修正。联系 FreeBSD 基本系统开发团队的主要方式是订阅 [FreeBSD 技术讨论邮件列表](https://lists.freebsd.org/subscription/freebsd-hackers)。对于第三方应用程序的移植，应该订阅 [FreeBSD ports 邮件列表](https://lis
对此我认为避免读者对邮件列表所讨论的语言中文还是英文产生混淆更为合适。亦或者可以在段末加一条译注：（译者注：上述邮件列表使用的语言均为英文）

2023-06-18 12:59 UTC, HeavySnowJakarta commented
> 1.3.4 一节“你所编译的每个 port 的完整原始文件都是动态检索的”这一句我没看懂。我觉得这么译不对劲。
> 1.2 概述一章“而不是硬编码行为的单体‘一体化’守护程序。”是否应再清楚些？举几个 systemd 之类的例子？

这两个问题待我去邮件列表咨询一下。

2023-06-18 13:30 UTC, HeavySnowJakarta commented
> Hello here I’m contributing to the simplified Chinese translation of the doc. I’m confused about two words of the first chapter:
> The full original distribution for each port you build is retrieved dynamically so you need only enough disk space to build the ports you want.
How should I understand “retrieved dynamically”? Why to say “so you need only enough disk space to build”?
> preferring composability instead of monolithic "all in one" daemons with hardcoded behavior.
How to understand “hardcoded behavior”? Is it to say what the daemon does is hard to revise?

但愿邮件列表是直接发给他给的那个邮箱就行的。

2023-06-18 13:33 UTC, ykla commented on di-1-zhang-jian-jie/1.3.-guan-yu-freebsd-xiang-mu.md
> +最后，但绝对非常重要地，最大的开发者群体是用户自己，他们几乎一直在向我们提供反馈和错误修正。联系 FreeBSD 基本系统开发团队的主要方式是订阅 [FreeBSD 技术讨论邮件列表](https://lists.freebsd.org/subscription/freebsd-hackers)。对于第三方应用程序的移植，应该订阅 [FreeBSD ports 邮件列表](https://lis
不应该在原文中插入无关的东西。

2023-06-18 13:33 UTC, ykla commented on di-1-zhang-jian-jie/1.3.-guan-yu-freebsd-xiang-mu.md
> +最后，但绝对非常重要地，最大的开发者群体是用户自己，他们几乎一直在向我们提供反馈和错误修正。联系 FreeBSD 基本系统开发团队的主要方式是订阅 [FreeBSD 技术讨论邮件列表](https://lists.freebsd.org/subscription/freebsd-hackers)。对于第三方应用程序的移植，应该订阅 [FreeBSD ports 邮件列表](https://lis
官方所有邮件列表语言都是英语。

2023-06-18 13:38 UTC, ykla commented
> 

邮件列表必须先订阅，才能发送。而且 FreeBSD doc邮件列表是没有任何用处的，里面没有任何人会回复你。他们是在闭门造车。——这里我指 doc 工程团队。

2023-06-19 01:55 UTC, HeavySnowJakarta commented on di-1-zhang-jian-jie/1.3.-guan-yu-freebsd-xiang-mu.md
> +最后，但绝对非常重要地，最大的开发者群体是用户自己，他们几乎一直在向我们提供反馈和错误修正。联系 FreeBSD 基本系统开发团队的主要方式是订阅 [FreeBSD 技术讨论邮件列表](https://lists.freebsd.org/subscription/freebsd-hackers)。对于第三方应用程序的移植，应该订阅 [FreeBSD ports 邮件列表](https://lis
我妥协了。但我始终认为应该加一条译注说明这些东西都是英语的。

2023-06-19 01:57 UTC, HeavySnowJakarta commented
现在应该可以顺利合并了。那两个问题我没有办法，只能搁置。

2023-06-19 02:03 UTC, ykla approved these changes

2023-06-19 02:03 UTC, merged