校对 2.9-3.4
FreeBSD-Ask/Handbook pull request #42
Opened 2022-06-11 09:01 UTC by ykla

校对 2.9-3.4

2022-06-11 10:08 UTC, das-rob3rt requested changes

2022-06-11 15:07 UTC, ykla commented on di-2-zhang-an-zhuang-freebsd/2.10.-gu-zhang-pai-chu.md
> +检查 FreeBSD 版本的硬件说明 (<https://www.freebsd.org/releases/>) 文件，以确定是否支持该硬件。如果硬件被支持，但出现了卡住或其他问题，请按照[配置 FreeBSD 内核](https://docs.freebsd.org/en/books/handbook/kernelconfig/index.html#kernelconfig)中的说明构建一个定
Check the Hardware Notes (https://www.freebsd.org/releases/) document for the version of FreeBSD to make sure the hardware is supported. If the hardware is supported and lock-ups or other problems occur, build a custom kernel using the instructions in Configuring the FreeBSD Kernel to add support for devices which are not present in the GENERIC kernel. The default kernel assumes that most hardware devices are in their factory default configuration in terms of IRQs, I/O addresses, and DMA channels. If the hardware has been reconfigured, a custom kernel configuration file can tell FreeBSD where to find things.

2022-06-11 15:08 UTC, ykla commented on di-2-zhang-an-zhuang-freebsd/2.10.-gu-zhang-pai-chu.md
> +如果系统在启动过程中探测硬件时挂起，或者在安装过程中表现得很奇怪，可能罪魁祸首是 ACPI。FreeBSD 在 i386 和 amd64 平台上广泛使用了系统的 ACPI 服务，如果在启动过程中检测到它，就可以帮助配置系统。不幸的是，ACPI 驱动程序和系统主板及 BIOS 固件中仍然存在一些问题。可以通过在第三阶段启动加载器中设置 `hint.acpi.0.disabled` 提示来禁用 AC
If the system hangs while probing hardware during boot, or it behaves strangely during install, ACPI may be the culprit. FreeBSD makes extensive use of the system ACPI service on the i386 and amd64 platforms to aid in system configuration if it is detected during boot. Unfortunately, some bugs still exist in both the ACPI driver and within system motherboards and BIOS firmware. ACPI can be disabled by setting the hint.acpi.0.disabled hint in the third stage boot loader:

2022-06-11 15:10 UTC, ykla commented on di-2-zhang-an-zhuang-freebsd/2.9.-wang-luo-jie-kou.md
> +无线网络是通过服务集标识（SSID）来识别的，这是一个简短而独特的名称。在扫描过程中会列出发现的 SSID，然后会对该网络可用的加密类型进行说明。如果所需的 SSID 没有出现在列表中，可选择 **Rescan** 再扫描一次。如果想要的网络仍然没有出现，请检查天线的连接是否正常，或尝试将电脑移到离接入点更近的地方，然后再扫描一次。
他想说的是天线。

2022-06-11 15:13 UTC, ykla commented on di-3-zhang-freebsd-ji-chu/3.3.-yong-hu-he-ji-ben-zhang-hu-guan-li.md
> +内置的 [su(1)](https://www.freebsd.org/cgi/man.cgi?query=su&sektion=1&format=html) 框架对于只有一个系统管理员的单一系统或小型网络来说效果很好。另一个选择是通过软件包或 ports 安装 [security/sudo](https://cgit.freebsd.org/ports/tree/security/sudo/p
The built-in [su(1)](https://www.freebsd.org/cgi/man.cgi?query=su&sektion=1&format=html) framework works well for single systems or small networks with just one system administrator. An alternative is to install the [security/sudo](https://cgit.freebsd.org/ports/tree/security/sudo/pkg-descr) package or port. This software provides activity logging and allows the administrator to configure which users can run which commands as the superuser.

2022-06-11 15:17 UTC, ykla commented on di-3-zhang-freebsd-ji-chu/3.2.-xu-ni-kong-zhi-tai-he-zhong-duan.md
> +FreeBSD 保留了从 `Alt+F1` 到 `Alt+F8` 的组合键，用于在虚拟控制台之间切换。使用 `Alt+F1` 切换到系统控制台（**ttyv0**），`Alt+F2` 访问第一个虚拟控制台（**ttyv1**），`Alt+F3` 访问第二个虚拟控制台（**ttyv2**），以此类推。当使用 Xorg 作为图形控制台时，该组合变为 `Ctrl+Alt+F1`，以返回到基于文本的虚拟
The key combinations Alt+F1 through Alt+F8 have been reserved by FreeBSD for switching between virtual consoles. Use Alt+F1 to switch to the system console (ttyv0), Alt+F2 to access the first virtual console (ttyv1), Alt+F3 to access the second virtual console (ttyv2), and so on. When using Xorg as a graphical console, the combination becomes Ctrl+Alt+F1 to return to a text-based virtual console.

2022-06-11 15:20 UTC, ykla commented on di-3-zhang-freebsd-ji-chu/3.2.-xu-ni-kong-zhi-tai-he-zhong-duan.md
> +FreeBSD 保留了从 `Alt+F1` 到 `Alt+F8` 的组合键，用于在虚拟控制台之间切换。使用 `Alt+F1` 切换到系统控制台（**ttyv0**），`Alt+F2` 访问第一个虚拟控制台（**ttyv1**），`Alt+F3` 访问第二个虚拟控制台（**ttyv2**），以此类推。当使用 Xorg 作为图形控制台时，该组合变为 `Ctrl+Alt+F1`，以返回到基于文本的虚拟
第1 个tty 是GUI（图形桌面会话）。

2022-06-12 01:09 UTC, das-rob3rt commented on di-2-zhang-an-zhuang-freebsd/2.10.-gu-zhang-pai-chu.md
> +检查 FreeBSD 版本的硬件说明 (<https://www.freebsd.org/releases/>) 文件，以确定是否支持该硬件。如果硬件被支持，但出现了卡住或其他问题，请按照[配置 FreeBSD 内核](https://docs.freebsd.org/en/books/handbook/kernelconfig/index.html#kernelconfig)中的说明构建一个定
> The default kernel assumes that most hardware devices are in their factory default configuration in terms of IRQs, I/O addresses, and DMA channels

默认的 FreeBSD 内核假定大多数硬件的中断请求、I/O 地址、DMA 通道的配置使用厂家的默认配置

> If the hardware has been reconfigured, a custom kernel configuration file can tell FreeBSD where to find things

如果你的硬件被魔改过，请修改内核配置文件来告诉 FreeBSD 如何应对这些特殊的硬件

2022-06-12 01:14 UTC, das-rob3rt commented on di-2-zhang-an-zhuang-freebsd/2.10.-gu-zhang-pai-chu.md
> +如果系统在启动过程中探测硬件时挂起，或者在安装过程中表现得很奇怪，可能罪魁祸首是 ACPI。FreeBSD 在 i386 和 amd64 平台上广泛使用了系统的 ACPI 服务，如果在启动过程中检测到它，就可以帮助配置系统。不幸的是，ACPI 驱动程序和系统主板及 BIOS 固件中仍然存在一些问题。可以通过在第三阶段启动加载器中设置 `hint.acpi.0.disabled` 提示来禁用 AC
> Unfortunately, some bugs still exist in both the ACPI driver and within system motherboards and BIOS firmware. ACPI can be disabled by setting the hint.acpi.0.disabled hint in the third stage boot loader

The "some bugs" right here is apparently not guaranteed to occur, it's rather something that CAN happen. However, the translation makes it sound like it MUST happen.

2022-06-12 03:50 UTC, merged