校对 3.7-3.8
FreeBSD-Ask/Handbook pull request #44
Opened 2022-06-13 08:55 UTC by ykla

2022-06-18 15:40 UTC, das-rob3rt requested changes
* di-3-zhang-freebsd-ji-chu/3.6.-ci-pan-jie-gou.md
* di-3-zhang-freebsd-ji-chu/3.8.-jin-cheng-he-shou-hu-jin-cheng.md
* di-4-zhang-an-zhuang-ying-yong-cheng-xu-ruan-jian-bao-he-ports/4.4.-shi-yong-pkg-jin-hang-er-jin-zhi-bao-guan-li.md
* di-4-zhang-an-zhuang-ying-yong-cheng-xu-ruan-jian-bao-he-ports/4.5.-shi-yong-ports.md

Please note that I haven't done reviewing those four files yet. I'm leaving them for tomorrow. Don't merge.

2022-06-18 15:40 UTC, das-rob3rt commented on di-4-zhang-an-zhuang-ying-yong-cheng-xu-ruan-jian-bao-he-ports/4.2.-ruan-jian-an-zhuang-de-gai-shu.md
> +软件包和 ports 都能解析依赖关系。如果使用软件包或 port 安装一个应用程序，而所依赖的库还没有安装，那么就会先自动安装这个库。
If the original text here says "binary package", we'd better respect that and use "二进制包" as well.

By saying "software package", it can either be in binary form or in source form.

2022-06-18 15:40 UTC, das-rob3rt commented on di-4-zhang-an-zhuang-ying-yong-cheng-xu-ruan-jian-bao-he-ports/4.2.-ruan-jian-an-zhuang-de-gai-shu.md
> +软件包和 ports 都能解析依赖关系。如果使用软件包或 port 安装一个应用程序，而所依赖的库还没有安装，那么就会先自动安装这个库。
But in the context FreeBSD, there seems to be no such thing as "source package", instead there are only Ports... So I'm leaving the phrase decision to you.

2022-06-18 15:40 UTC, das-rob3rt commented on di-4-zhang-an-zhuang-ying-yong-cheng-xu-ruan-jian-bao-he-ports/4.2.-ruan-jian-an-zhuang-de-gai-shu.md
> +- 有些人不信任二进制分发，或者喜欢通读源代码，以寻找潜在的问题。
I've seen such persons in my real life...

2022-06-18 15:40 UTC, das-rob3rt commented on di-4-zhang-an-zhuang-ying-yong-cheng-xu-ruan-jian-bao-he-ports/4.2.-ruan-jian-an-zhuang-de-gai-shu.md
> +- 有些人不信任二进制分发，或者喜欢通读源代码，以寻找潜在的问题。
I've seen such persons in my real life...

2022-06-18 15:50 UTC, ykla commented on di-4-zhang-an-zhuang-ying-yong-cheng-xu-ruan-jian-bao-he-ports/4.2.-ruan-jian-an-zhuang-de-gai-shu.md
> +软件包和 ports 都能解析依赖关系。如果使用软件包或 port 安装一个应用程序，而所依赖的库还没有安装，那么就会先自动安装这个库。
应该是一个意思。

2022-06-18 15:52 UTC, ykla commented
哦，还有 https://github.com/FreeBSD-Ask/Handbook/issues/45

2022-06-22 14:27 UTC, das-rob3rt requested changes
Sorry for the late review, please leave comments if you have any questions.

2022-06-22 14:27 UTC, das-rob3rt commented on di-4-zhang-an-zhuang-ying-yong-cheng-xu-ruan-jian-bao-he-ports/4.4.-shi-yong-pkg-jin-hang-er-jin-zhi-bao-guan-li.md
> +要从季度分支切换到最新分支，请运行以下命令：
```suggestion
要从季度分支切换到最新分支，请首先运行以下命令：
```

2022-06-22 14:27 UTC, das-rob3rt commented on di-4-zhang-an-zhuang-ying-yong-cheng-xu-ruan-jian-bao-he-ports/4.4.-shi-yong-pkg-jin-hang-er-jin-zhi-bao-guan-li.md
> +关于安装在系统上的软件包的信息可以通过运行 `pkg info` 来查看，当直接运行没有任何参数时，它将列出所有安装的软件包或指定的软件包的版本。
> 它将列出所有安装的软件包或指定的软件包的版本

Consider adding a side note to remind user that `pkg info` without a package name can be flooding their terminal or even cause their SSH session to freeze.

2022-06-22 14:27 UTC, das-rob3rt commented on di-4-zhang-an-zhuang-ying-yong-cheng-xu-ruan-jian-bao-he-ports/4.5.-shi-yong-ports.md
>  建议在卸载 port 的过程中阅读这些信息。如果这个 port 有任何依赖它的应用程序，这些信息将被显示出来，但卸载将继续进行。在这种情况下，为了防止依赖关系被破坏，重新安装该应用程序可能会更好。
```suggestion
建议在卸载 port 的过程中阅读这些信息。如果这个 port 有任何依赖它的应用程序，这些信息将被显示出来，但卸载将继续进行。在这种情况下，为了防止依赖关系被破坏，建议重新安装该应用程序。
```

2022-06-22 14:43 UTC, ykla commented on di-3-zhang-freebsd-ji-chu/3.8.-jin-cheng-he-shou-hu-jin-cheng.md
> +有些程序的设计不是为了在用户连续输入的情况下运行，而是一有机会就断开与终端的连接。例如，网络服务器响应的是网络请求，而非用户输入。邮件服务器是这种类型的应用程序的另一个例子。这些类型的程序被称为 *守护进程* 。守护进程这一术语来自希腊神话，代表了一个既非善也非恶的存在，它在无形中执行着有用的任务。这就是 BSD 的吉祥物是一个穿着帆布鞋、拿着干草叉、看起来很欢快的守护者的原因。
BSD 的吉祥物都是 `小恶魔`

2022-06-22 14:49 UTC, merged